### ISSUE TITLE
Reg: Mapping Async Request from Client to oatpp-consul

### ISSUE THREAD

**Issue by bkannadassan** [oatpp/oatpp-consul#3]
Hi Leonid,

  I went through the previous query on Async but didn't get a response what I have been looking for, would much appreciate if you clarify on the same..

`executor.execute<SendDtoCoroutine>(client, "message1", 10000);`

Here we are calling async, Assuming for consul we do the same. We planning to expose a wrapper function over oatpp, which allows a user to send multiple requests. I would like to know when the response received how can I map and reply back to user application ?. Can you please let me know how this can be done ?.

rgds
Balaji Kamal Kannadassan

**Comment by bkannadassan** [comment]
Please do ignore the same I have figured it out. Looks like we can add additional attributes 

```
    SendDtoCoroutine(const std::shared_ptr<PWApiClient> client,
                    const oatpp::String& message,
                    v_int32 code, v_int32 idx)
      : m_client(client)
      , m_message(message)
      , m_code(code)
    {}
```

`  g_executor->execute<SendDtoCoroutine>(client, "message1", 10000, **1**);`

In above I have added one additional attribute in the end called idx and will use that as reference..

rgds
Balaji Kamal Kannadassan

**Comment by lganzzzo** [comment]
Hey @bkannadassan ,

You are absolutely right, you may define custom constructors for coroutines.

Good you found it before I managed to answer :)

Best Regards,
Leonid
