### ISSUE TITLE
Reg: Consul Session Creation getting rejected with 404

### ISSUE THREAD

**Issue by bkannadassan** [oatpp/oatpp-consul#4]
Hi Leonid,

   I see KV GET/SET all working fine but I see an issue with session creation with the consul. What I see is in normal curl there is an offset of 5 bytes in the end and not sure if that's the issue.

```cpp
 API_CALL_ASYNC("PUT", "v1/sesion/{parameter}", doPUTSessionCoroutineDtoAsync, PATH(String, parameter), BODY_DTO(consulSessionCreateData::ObjectWrapper, body))

  class PUTSessionCoroutine: public oatpp::async::Coroutine<PUTSessionCoroutine> {
  private:
    std::shared_ptr<PWRestClient> m_client;
    oatpp::String m_key, m_value;
    CreateSess *m_createsess;
    v_int32 m_reqidx;
  public:
    PUTSessionCoroutine(const std::shared_ptr<PWRestClient> client,
                    const oatpp::String& key,
                    const oatpp::String& value,
                    CreateSess *sess, v_int32 req_idx)
      : m_client(client)
      , m_key(key)
      , m_value(value)
      , m_reqidx(req_idx)
      , m_createsess(sess)
    {}
    Action act() override {
      if (strcmp(m_key->c_str(), "create") == 0) {
        auto dto = consulSessionCreateData::createShared();
        dto->name=m_createsess->name.c_str();
        return m_client->doPUTSessionCoroutineDtoAsync(m_key,dto).callbackTo(&PUTSessionCoroutine::onResponse);
      } else {
        return m_client->doPUTSessionCoroutineAsync(m_key,m_value).callbackTo(&PUTSessionCoroutine::onResponse);
      }
    }
    Action onResponse(const std::shared_ptr<Response>& response) {
      return response->readBodyToStringAsync().callbackTo(&PUTSessionCoroutine::onBody);
    }
    Action onBody(const oatpp::String& body) {
      OATPP_LOGD(TAG, "[doPUTSessionCoroutineAsync] data='%s' %d", body->c_str(), m_reqidx);
      return finish();
    }

  class consulSessionCreateData : public oatpp::data::mapping::type::Object {
    DTO_INIT(consulSessionCreateData, Object)
    DTO_FIELD(String, lockdelay, "LockDelay");
    DTO_FIELD(String, name, "Name");
    DTO_FIELD(List<String>::ObjectWrapper, checks, "Checks");
    DTO_FIELD(String, behavior, "Behavior");
    DTO_FIELD(String, ttl, "TTL");
  };
==========================================
*   Trying 127.0.0.1:8500...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8500 (#0)
> PUT /v1/sesion/create HTTP/1.1
Host: 127.0.0.1:8500
Accept: */*
Transfer-Encoding: chunked

* Signaling end of chunked upload via terminating chunk.
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Date: Thu, 15 Aug 2019 06:28:56 GMT
< Content-Length: 0
<
* Connection #0 to host 127.0.0.1 left intact
 D | 1565850536932924| PWRestClient:[doPUTSessionCoroutineAsync] data='' 456

```
Same if I perform via curl command it works..
```
[root@balaji-nomad-consul-1 build]# cat payload.json
{"Name": "my-service-lock12345"}
[root@balaji-nomad-consul-1 build]# curl -H "Transfer-Encoding: chunked"  --request PUT     --data @payload.json     http://127.0.0.1:8500/v1/session/create
{"ID":"2b038b52-5aa3-3a16-b3f8-d118787ed6a2"}[root@balaji-nomad-consul-1 build]#
```
Is there anything I am missing on the same ?.

rgds
Balaji Kamal Kannadassan

**Comment by bkannadassan** [comment]
To add to the above query, I came across consul issue in handling chunked data for session create when in 2 packets. Checking with them if they can resolve, looks like an issue with chunked data has been pending for more than 2 years. Is it possible to turn off the chunked data for certain request ?, basically our data are so small.
[https://groups.google.com/forum/#!searchin/consul-tool/chunked%7Csort:date/consul-tool/c8latJb8Yb4/L0XF-yuMAwAJ](url)
rgds
Balaji Kamal Kannadassan

**Comment by lganzzzo** [comment]
Hello @bkannadassan ,

It should not be the issue with chunked data because oatpp client will NOT send DTO request as chunked. Oatpp client sends DTO request with `Content-Length` header.

---

> Same if I perform via curl command it works..

```bash
==========================================
*   Trying 127.0.0.1:8500...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8500 (#0)
> PUT /v1/sesion/create HTTP/1.1
Host: 127.0.0.1:8500
Accept: */*
Transfer-Encoding: chunked

* Signaling end of chunked upload via terminating chunk.
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Date: Thu, 15 Aug 2019 06:28:56 GMT
< Content-Length: 0
<
```

This is a curl command output right?
Can you please add a command itself here too.

---

How this command differs from the previous one?:
```bash
curl -H "Transfer-Encoding: chunked"  --request PUT     --data @payload.json     http://127.0.0.1:8500/v1/session/create
{"ID":"2b038b52-5aa3-3a16-b3f8-d118787ed6a2"}
```

---

Please check here for the response status code. Make sure it is `200`:
```cpp
    Action onResponse(const std::shared_ptr<Response>& response) {
      OATPP_ASSERT_HTTP(response->getStatusCode() == 200, Status::CODE_500, "Internal Error");
      return response->readBodyToStringAsync().callbackTo(&PUTSessionCoroutine::onBody);
    }
```

I suspect that you get NOT `200` from Consul. And thats why response body is empty.



Best Regards,
Leonid

**Comment by bkannadassan** [comment]
Hi Leonid,

  I can do

**Comment by bkannadassan** [comment]
Hi Leonid,
    I can do 
`curl -H "Transfer-Encoding: chunked"  --request PUT     --data @payload.json     http://127.0.0.1:8500/v1/session/create`

 here I was trying to replicate what I saw from the packets captured in oatpp. Btw I am not getting 200 but I am getting 404 not found failed. 
Btw oatpp client is sending it as Chunked. Please find below link where I have attached captured packet.

`curl -H "Transfer-Encoding: chunked"  --request PUT     --data @payload.json     http://127.0.0.1:8500/v1/session/create`
1) chunkedsuccess.pcap{executed from curl comand}

`curl --request PUT     --data @payload.json     http://127.0.0.1:8500/v1/session/create`
2) success.pcap { curl without chunked}

`Sent via oatpp`
3) sessioncreatefailed.pcap  {oatpp client }, btw below is the text of packet sent from oatpp.

```
Hypertext Transfer Protocol
    PUT /v1/sesion/create HTTP/1.1\r\n
    Host: 127.0.0.1:8500\r\n
    <Host: 127.0.0.1:8500\r\n>
    Accept: */*\r\n
    <Accept: */*\r\n>
    Transfer-Encoding: chunked\r\n
    <Transfer-Encoding: chunked\r\n>
    \r\n
    [Full request URI: http://127.0.0.1:8500/v1/sesion/create]
    <Request: True>
    [HTTP request 1/1]
    [Response in frame: 8]

Hypertext Transfer Protocol
    File Data: 33 bytes
    Data (33 bytes)
        Data: 31620d0a7b224e616d65223a20226d792d73657276696365...
        [Length: 33]

```


[https://gofile.io/?c=2XnKg7](url)
have attached zip file of different capture in this link. Please let me know if I am missing something..

rgds
Balaji Kamal Kannadassan

**Comment by lganzzzo** [comment]
Hey @bkannadassan ,

I'll try to reproduce it and I'll get back to you. 

BTW what oatpp version are you using ?

Regards,
Leonid

**Comment by bkannadassan** [comment]
Hi Leonid,

  Sure, Btw I am using the latest version of all oatpp i.e 0.19.7. Btw fyi consul has asked me to raise a bug so have raised one in hashicorp so they are also checking on the same. Please let me know if you need any further information on the same.

rgds
Balaji Kamal Kannadassan

**Comment by lganzzzo** [comment]
Thanks for the info. I'll try to reproduce it.

**Comment by bkannadassan** [comment]
Hi Leonid, 
  Would like to know if you got a chance to check the same ?. Without session creation leader election not possible with consul. Can you suggest us a solution on the same ?.
Rgds
Balaji Kamal kannadassan

**Comment by lganzzzo** [comment]
Hey @bkannadassan ,

I reproduced and found the error ... it's typo in the endpoint name :)

you have:
```cpp
API_CALL_ASYNC("PUT", "v1/sesion/{parameter}", doPUTSessionCoroutineDtoAsync, PATH(String, parameter), BODY_DTO(consulSessionCreateData::ObjectWrapper, body))
```

but it should be:
```cpp
API_CALL_ASYNC("PUT", "v1/session/{parameter}", doPUTSessionCoroutineDtoAsync, PATH(String, parameter), BODY_DTO(consulSessionCreateData::ObjectWrapper, body))
```

`sesion` ---> `session`

No chunked request/responses here.
After I fixed typo everything worked.

Regards,
Leonid

**Comment by bkannadassan** [comment]
Thanks a TON and sorry for the confusion.

rgds
Balaji Kamal Kannadassan
