### ISSUE TITLE
Build conflict with Microsoft atlbase.h

### ISSUE THREAD

**Issue by ke9** [oatpp/oatpp-consul#6]
Visual Studio 2015, debug x64 configuration

The constant **constexpr static const char* DELETE = "DELETE";** in oatpp-consul/rest/CLient.hpp conflicts something in atlbase.h. Did not have time to find this define in the ATL code. 

Currently doing **#undef DELETE** before including Client.hpp. Maybe prefixing this constant with something could do the trick. 

Maybe the VS2015 C++ compiler is the issue?

**Comment by lganzzzo** [comment]
Hello @ke9 ,

You mean this delete right? https://github.com/oatpp/oatpp-consul/blob/master/src/oatpp-consul/rest/Client.hpp#L45

I think we can do renaming to something like "HTTP_DELETE".

I'll ping you once done.

Regards,
Leonid

**Comment by ke9** [comment]
yes exactly!

**Comment by lganzzzo** [comment]
Hey @ke9 ,

Please verify the fix. - in the branch https://github.com/oatpp/oatpp-consul/tree/rename_constants_in_rest_client

I'll merge the PR once verified.

Regards,
Leonid

**Comment by ke9** [comment]
I fetch your fix and it built fine, thank you!
Marco

**Comment by lganzzzo** [comment]
Merged!
